---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.27.0
    env:
      TZ: "Europe/Minsk"
      ZIGBEE2MQTT_DATA: /data
      ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyACM0
      ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: true
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
      ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: true
      ZIGBEE2MQTT_CONFIG_advanced_last_seen: ISO_8601
      ZIGBEE2MQTT_CONFIG_advanced_rtscts: false
      ZIGBEE2MQTT_CONFIG_advanced_baudrate: 115200
    securityContext:
      privileged: true
    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/ttyACM0
    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/ttyACM0
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-basic-auth@kubernetescrd
        hosts:
          - host: "z.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "z.${SECRET_DOMAIN}"
            secretName: "${CLUSTER_DOMAIN_CERT}"
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-pvc
        mountPath: /data
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
