apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pvc
spec:
  storageClassName: zigbee2mqtt-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-volume
  labels:
    type: local
spec:
  storageClassName: zigbee2mqtt-storageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/zigbee2mqtt"
