---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: focalboard
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: focalboard
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://artifacthub.io/packages/helm/k8s-at-home/focalboard
  values:
    image:
      repository: mattermost/focalboard
      pullPolicy: IfNotPresent
      tag: 7.11.4

    persistence:
      config:
        enabled: true
        existingClaim: focalboard-pvc

    env:
      - name: FOCALBOARD_PORT
        value: "8000"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: base-auth-global
        hosts:
          - host: "board.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "board.${SECRET_DOMAIN}"

    # See the Administrator's Guide for config reference: https://www.focalboard.com/guide/admin/
    config: |
      {
        "serverRoot": "http://localhost:8000",
        "port": 8000,
        "dbtype": "sqlite3",
        "dbconfig": "/data/focalboard.db",
        "dbtableprefix": "",
        "postgres_dbconfig": "dbname=focalboard sslmode=disable",
        "test_dbconfig": "file::memory:?cache=shared",
        "useSSL": false,
        "webpath": "./pack",
        "filesdriver": "local",
        "filespath": "/data/files",
        "telemetry": false,
        "prometheus_address": ":9092",
        "webhook_update": [],
        "session_expire_time": 2592000,
        "session_refresh_time": 18000,
        "localOnly": false,
        "enableLocalMode": true,
        "localModeSocketLocation": "/var/tmp/focalboard_local.socket",
        "authMode": "native",
        "logging_cfg_file": "",
        "audit_cfg_file": "",
        "enablepublicsharedboards": true
      }
