---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard-pvc
spec:
  storageClassName: focalboard-storageclass
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: focalboard-volume
  labels:
    type: local
spec:
  storageClassName: focalboard-storageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/focalboard"
