---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 60m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 60m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.6.3
    env:
      TZ: "Europe/Minsk"
    envFrom:
      - secretRef:
          name: home-assistant-env
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-pvc
        mountPath: /config
    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: ${SECRET_HASS_MYSQL_DATABASE}
        username: ${SECRET_HASS_MYSQL_USER}
        password: ${SECRET_HASS_MYSQL_PASSWORD}
        rootPassword: ${SECRET_HASS_MYSQL_ROOT_PASSWORD}
      primary:
        persistence:
          enabled: true
          existingClaim: hassdb-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ha.${SECRET_DOMAIN}"
            secretName: "${CLUSTER_DOMAIN_CERT}"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
