apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:n2++u6fDWq29ZyteMw==,iv:87GSwNUFsAv33I4jyTRUqcKjC9K3hiH3U0Sx4CTkV/Y=,tag:h0jT5FQ6zbM9vmUI7FLeHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-17T00:20:55Z"
    mac: ENC[AES256_GCM,data:SvKCxD9PvBmstbWhJ5EcSmD5WBVjSE6oSeBruGUyYTMBbZYzOxQqtBjVl0xcfHU9CedJyx+HfR9/RLi0VhUG8PUitvmv5Lx73hh7VCw2G7Nso6JeM1Pob3NofnIRfUw5VkyE7PKy8ssFGKW++k2kOXKYXg7ZK1AVKK6/IfSjJJ4=,iv:5FU2lVz3hhE7qE9rgmuSSF7GNKL8qoeR+fmrOYhqYOY=,tag:VFT5PxK26bQbsVLuScykFA==,type:str]
    pgp:
        - created_at: "2021-12-17T00:20:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwKPZcbHKm2iAQ/8CxLbJZM2A3PKLIuZjmN7wNVBl2VQKBKM3fw27BrSZrhi
            4FjyckuUT3IY83RJ6iuDqo0Rq9H4Zflpob3kjWS/UKBUwY/nbTsewXGCp1VyTbyI
            FkzaCBErMuVaVpIZH/4wbc0Me5Hki0C5JwRIajvqEDeB1SX20kVEg8+6RccRyYmJ
            dnEKDAgUx0n0L+GH7PCLGDaG/SaJoD8x6SQT4iw28rZ/ILqdWQZ/6nZw+wiII3hX
            rUZ59xGawIuW4Jo3LjFdbiTFqNnrBjbKep3bC1dFNLIlS5I1LiBU40rE2or7XkOx
            yDkIhKnoGxz4uBYCgzlAI43ioGak2yteA+sHHG4OIg/3U4d94bOCqGY3RU+8UfWu
            iUZCvs2Mn9fXbVrAvd/eEQRF8dIX3Qhx3W/ElAWC2lcdlp465tcB8i8Hpc8CSsJZ
            31wxN1zyD/pfdDhH5jb/YmMwlR3X5ocUmyTdKgd+lHH81iATCRt2A/PYEfDyvXKw
            mCJ9QrvozPtmwRkxRMlXCH5LyyhhozOpLTAWeeAmpj3GILWStG2arXyhlL8JV9/t
            JKwOgcy/k0V67rAtYT4fwV8FZ94+lg3MvUDIe8J3hBJtLzeRE3C4XiQJbkZ4y161
            Vsjvwu8X0iga8ZpHPLmERhMn06Rh3spZa7ft3j+wyQ8u1wtrZfz3uB9AAZWvneTS
            XgHhAKEOIkZ/737WLpfkRnTVNITjDr6XwwFX4++Usl/6lb0tI3czipMCLhcN6/pL
            8ltH6JU5UsbqcoYuoIIB1gHdg0Azdeli5GybyO72oKhH4I83MoJiKt7q5WCuNjE=
            =JF87
            -----END PGP MESSAGE-----
          fp: 1EB49F4A2588BBFBBCCA28B87DAE506C2FB93A3D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
