apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
secretGenerator:
  - name: config-test
    namespace: flux-system
    files:
      - cluster-secret.yaml