---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate-ignore: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
# ONLY FOR CHART <v0.12.1
#  values:
#    configInline:
#      address-pools:
#        - name: default
#          protocol: layer2
#          addresses:
#            - "${METALLB_LB_RANGE}"
