---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate-ignore: registryUrl=https://metallb.github.io/metallb
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    crds:
      enabled: true
