---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-pvc
spec:
  storageClassName: adguard-config-storageclass
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-config-volume
  labels:
    type: local
spec:
  storageClassName: adguard-config-storageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/adguard-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-pvc
spec:
  storageClassName: adguard-data-storageclass
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-data-volume
  labels:
    type: local
spec:
  storageClassName: adguard-data-storageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/adguard-data"
