---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: adguard-config-storageclass
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: adguard-data-storageclass
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-config-volume
  labels:
    type: local
spec:
  storageClassName: adguard-config-storageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/adguard-config"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-data-volume
  labels:
    type: local
spec:
  storageClassName: adguard-data-storageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/adguard-data"
