---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  releaseName: zigbee2mqtt
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.22.1
    env:
      TZ: "America/New_York"
      ZIGBEE2MQTT_DATA: /data
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-pvc
        mountPath: /data

    config:
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://192.168.0.170"
        user: ${TEST_SECRET}
        password: ${TEST_SECRET}
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      advanced:
        pan_id: 6754
      frontend:
        port: 8080
      expirimental:
        new_api: true