apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-pvc
spec:
  storageClassName: esphome-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-volume
  labels:
    type: local
spec:
  storageClassName: esphome-storageclass
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/samedi/microk8s-gitops/data/esphome"
