---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: networking
  name: traefik-authentik
spec:
  routes:
    - kind: Rule
      match: "Host(`https://traefik.${SECRET_DOMAIN}`) && PathPrefix(`/akprox/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-authentik-embedded-outpost
          port: 9000
