---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 10m0s
  releaseName: linkerd
  chart:
    spec:
      # renovate: registryUrl=https://helm.linkerd.io/stable
      chart: linkerd2
      version: 2.11.3
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: global.identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    installNamespace: false
    identity:
      issuer:
        crtExpiry: "2022-01-15T22:43:06Z"
