apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    METALLB_LB_RANGE: ENC[AES256_GCM,data:3nNUnqBU29XqKUxDTaidRcxDxvnlSwh1vRdl,iv:GZjpQCTgOjJAahSbO9BaQ+gddbG1hRkWxt6laHM/960=,tag:JcwoBCf0FMXXpGRSolSDJg==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:jb9B6qaA4qlegMTeSA==,iv:wJm49o5LHKpGa+66qm49gAv7j8wl70TFq8bgiEi2PEs=,tag:zfxC1QZUSnl5yFh0RozKxw==,type:str]
    SVC_TRAEFIK_ADDR: ENC[AES256_GCM,data:59LwevKoYsuZU4C2mA==,iv:GdeXWtmGhIpmIbJL+6AGo6vm5xxHEYcc4zKp9dK2BGs=,tag:y2JBYJUgPGxXZc4sqsqsUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-20T01:42:53Z"
    mac: ENC[AES256_GCM,data:m8eT+SzO7JopOsepTiM1O4eq1VY9qQAEnSCbPdyTIMeJnhjW2LXnR8/CorEvXTcnXLhRV39AojW+SbVmB2hFZ/ChEKqKM2NWQGPhsFD4HkAKG2Isw+9oX2v0GlS81FF5Ay3h++2vG3bL7EkIt3kxwEaQEHKarnL/zZE5B/B+NoQ=,iv:yXptSkCsZDrGdm2uY9FTYqNOhgob+pPwOXIl6WwCvSQ=,tag:0TemhxhWPOS4IrWTGhtbVQ==,type:str]
    pgp:
        - created_at: "2021-12-20T01:42:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwKPZcbHKm2iAQ/9GFs4WWUWcl9JygRUhk32R2Fc9uaYq2mYXqhH9hsNOKVV
            ywLL3Rr4Hky39Hh+pNQLLxLLAv5nNnWTkPF2S4c3F540B/tsI+ekd1ow/078vDBL
            za4l9z/u2g6QWKgq0UiJl1D8jIpljqkFyBCj5aXsIbgJX14MiXg+pjSzdj4vf0in
            2rBGHQ9JW/rKaEljqMtLVZKYo4sJJN8zkPYDJO9eK4wsp54oBllfGDgU2xg7kDAO
            6hdSs7HOFOTPK3Mf+oAkivIdmi/hsLWG17ab7o5+DxY/fuaqmY5H2hD5eDqD6ely
            uVtR4kccWvcex9qVPh2lMWi+nAdytbOJ/8MR8Y5ebxmCX1Tkdfe/Aig8cmWwXJ/s
            xN9LA7KDYQcqzDITwG/Mk8f2SKBDugbA8Re84VmaPXIE0LLYs2baw8V0N+JRk7Rm
            XkM/BUAYKLWyE8sspAHd7wq8LRv/DMn73EGAv0toxGUWc1yWue2Zn8mQ5+koyZF3
            Mx/wukiKeVbvaMK5sZpxBqfjwEKpejaYFgmbrbPhQAlS1WeZeuHUzjup8Ckn+v5N
            lQrgDGn322PxvzFIO3F7CdI4mq98lTeZUJOAC6c4xDn4TgjxozBER/mB8fE1uE8V
            oO7G123DNCnmppQUsA54ungPDN0ngiQAaGdL0rG7/nF9jtBoHHeRMFRYrDMDLWPS
            XgHQEA/hFZX6KCyLEEL6mnxJR6larPEl2I+PBtM/2vboGFNIhNvBxBb9obkMrd4P
            jzP0hKONH67Tz79XcKs3xqyv0Ef7PmaASF4Ybhh+JpnAgwYBnmf1Wq6Pxx91udo=
            =U51P
            -----END PGP MESSAGE-----
          fp: 1EB49F4A2588BBFBBCCA28B87DAE506C2FB93A3D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
