apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
spec:
  storageClassName: home-assistant-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv-volume
  labels:
    type: local
spec:
  storageClassName: home-assistant-storageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/samedi/microk8s-gitops/home/zigbee2mqtt/testvolume"