apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://metallb.github.io/metallb chart=metallb
  - https://github.com/metallb/metallb/config/crd?ref=v0.13.10
