---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.appscode.com/stable/
      chart: kubed
      version: v0.13.2
      sourceRef:
        kind: HelmRepository
        name: appscode-charts
        namespace: flux-system
  values:
    enableAnalytics: false
    config:
      clusterName: microk8s
