---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: networking
  annotations:
    # Sync wildcard certificate across namespaces
    kubed.appscode.com/sync: "true"
spec:
  defaultCertificate:
    secretName: "${CLUSTER_DOMAIN_CERT}"
