---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://helm.releases.hashicorp.com

