---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "letsencrypt-wildcard-production-tls"
  namespace: default
spec:
  secretName: "letsencrypt-wildcard-production-tls"
  issuerRef:
    name: "letsencrypt-production"
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
