---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: cert-manager
  annotations:
    # Sync wildcard certificate across namespaces
    kubed.appscode.com/sync: "true"
spec:
  secretName: "${CLUSTER_DOMAIN_CERT}"
  issuerRef:
#    name: letsencrypt-staging
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
    - "*.home.${SECRET_DOMAIN}"
    - "*.pub.${SECRET_DOMAIN}"
