---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: cert-manager
spec:
  secretName: "${CLUSTER_DOMAIN_CERT}"
  issuerRef:
    name: letsencrypt-staging
    #name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - '${CLUSTER_DOMAIN}'
    - '*.${CLUSTER_DOMAIN}'
    - '*.home.${CLUSTER_DOMAIN}'
    - '*.pub.${CLUSTER_DOMAIN}'
