apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-sso
  namespace: networking
  labels:
    app: traefik-sso
spec:
  template:
    metadata:
      labels:
        name: traefik-sso
        app: traefik-sso
    spec:
      containers:
        - name: traefik-sso
          image: thomseddon/traefik-forward-auth:2
          imagePullPolicy: Always
          env:
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-sso
                  key: GOOGLE_OAUTH_CLIENT_ID
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-sso
                  key: GOOGLE_OAUTH_SECRET_KEY
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-sso
                  key: GOOGLE_OAUTH_ENTROPY
            - name: COOKIE_DOMAIN
              value: "${SECRET_DOMAIN}"
            - name: AUTH_HOST
              value: "auth.${SECRET_DOMAIN}"
            - name: INSECURE_COOKIE
              value: "false"
            # - name: URL_PATH
            #   value: /_oauth
            - name: WHITELIST
              value: joooostb@gmail.com
            - name: WHITELIST
              value: joooostb@gmail.com
            - name: LOG_LEVEL
              # TODO: error
              value: debug
          ports:
            - containerPort: 4181
---
kind: Service
apiVersion: v1
metadata:
  namespace: networking
  name: traefik-sso
spec:
  selector:
    app: traefik-sso
  ports:
    - protocol: TCP
      port: 4181
      targetPort: 4181
