name: Flux - Update GOTK Components

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  flux-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Update Flux components
        id: update
        run: |
          UGLY_VERSION="$(flux -v)"
          VERSION="v${UGLY_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --network-policy=false \
            --export > ./cluster/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"
      - name: Create pull request for Flux update
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "flux/update-${{ steps.update.outputs.flux_version }}"
          delete-branch: true
          title: "Update flux components to ${{ steps.update.outputs.flux_version }}"
          signoff: true
          committer: "Yauheni <muspelheim@users.noreply.github.com>"
          author: "Yauheni <muspelheim@users.noreply.github.com>"
          assignees: "muspelheim"
          commit-message: "Update flux components to ${{ steps.update.outputs.flux_version }}"
          body: |
            Signed-off-by: Yauheni <muspelheim@users.noreply.github.com>
          labels: flux/update
