---
name: Schedule - Update Helm Release Renovate annotations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-helm-release-annotations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./"
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-annotations
          delete-branch: true
          title: "Update renovate annotations"
          signoff: true
          committer: "Yauheni <muspelheim@users.noreply.github.com>"
          author: "Yauheni <muspelheim@users.noreply.github.com>"
          assignees: "muspelheim"
          commit-message: "Update renovate annotations"
          body: |
            Update Helm Releases in order for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations