---
name: Schedule - Update Helm Release Renovate annotations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-helm-release-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./"
          # Folders to exclude such as those use includes (Example: Ansible Vault)
          exclude-folders: './ansible'
          # Turn on debug logging
          debug: 'yes'
          # Do not alter Helm Release files
          dry-run: 'no'
          # Tolerate yaml files with errors instead of aborting on errors
          tolerate-yaml-errors: 'no'

      - name: Create pull request for HelmRelease annotations
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: helm-release-annotations
          delete-branch: true
          title: "[Renovate] create helmrelease annotations"
          signoff: true
          committer: "Yauheni <muspelheim@users.noreply.github.com>"
          author: "Yauheni <muspelheim@users.noreply.github.com>"
          assignees: "muspelheim"
          commit-message: "Create RenovateBot helmrelease annotations"
          body: |
            Update Helm Releases in order for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations
